apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytest
  namespace: fast-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytest
  template:
    metadata:
      labels:
        app: ytest
    spec:
      containers:
        - name: ytest-container
          image: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/global/fast/ytest:v1.0
          ports:
            - containerPort: 8080
